### ISSUE TITLE
Is it best practice to use sessions?

### ISSUE THREAD

**Issue by DarkLite1** [Azure-Samples/active-directory-javascript-nodejs-webapi-v2#14]
## Library

- [x] `@azure/msal-browser@2.1.0`

## Description

I've asked the same [question on StackOverflow](https://stackoverflow.com/questions/63464229/are-sessions-needed-for-passport-azure-ad-with-graphql) without any response so I'll try it here again.

I'm very new to web development but I've manged to set up a [client][1] and [server][2] app. The front-end uses [msal.js][3] to authenticate the user to Azure AD and the backend receives the `access_token` and verifies if the token is valid with [passport-azure-ad][4]. This is the [token flow][5]:
[![enter image description here][6]][6]

So far all is working fine except that I'm wondering how it would work on heavy load. In the [Microsoft example][7] they set the `session` to `false`. 

```javascript
// API endpoint
app.get("/hello",
    passport.authenticate('oauth-bearer', {session: false}),
```

This probably makes passport verify each and every call. Might this be an issue when invoked many times? We use `passport` as middlewware for graphql queries, nutations, resolvers, ... 

```javascript
  app.use(passport.initialize())
  passport.use(bearerStrategy)

  app.use(
    passport.authenticate('oauth-bearer', { session: false }),
    (req, _res, next) => {
      console.log('User info: ', req.user)
      console.log('Validated claims: ', req.authInfo)
      next()
    }
  )
```

This is a bit unclear from the docs of the bearerStrategy for our `v2` endpoint. If this becomes an issue it might be needed to create a graphql `login` and `logout` resolver that is only called when a user logs in and set up a `session` on the backend. 

Thank you for helping to clear up my confusion. 

  [1]: https://github.com/DarkLite1/hip
  [2]: https://github.com/DarkLite1/backend
  [3]: https://github.com/AzureAD/microsoft-authentication-library-for-js
  [4]: https://github.com/AzureAD/passport-azure-ad
  [5]: https://docs.microsoft.com/en-us/azure/active-directory/azuread-dev/v1-oauth2-client-creds-grant-flow#client-credentials-grant-flow-diagram
  [6]: https://i.stack.imgur.com/DgNa8.png
  [7]: https://github.com/Azure-Samples/active-directory-javascript-nodejs-webapi-v2/blob/master/index.js

**Comment by derisen** [comment]
@DarkLite1 as far as I know, the best practice for RESTful APIs is to be stateless i.e. each request should contain all the information that the API needs to decide whether and how to respond. As such, sessions are not recommended for REST APIs, in particular with respect to scalability (e.g. your API should be able to handle requests from any client type, some of which might not be able to establish a session). Of course, this might be in conflict with your performance needs. In that case, perhaps you should reconsider your app topology -a web application, instead of SPA + web API, might be the better approach for you.

**Comment by DarkLite1** [comment]
Thank you for the clarification @derisen . For me personally it would be a lot easier to not be using sessions, setting up cookies, maintaining the session store, ... . But, when using a session on the backend and having a `login` graphql mutation called by the client only once, than Azure AD will also be called only once to verify the token and from that point on a session would be started to avoid calling Azure AD multiple times to verify the token.

Verifying the token with `passport.authenticate()` and `session: false` for every call is fine by me. I'm just wondering at which point Azure AD will say "Hey man, you're sending us too many verification requests, we're baling out!".

Could you elaborate a bit on this? How will Azure handle so many requests?

**Comment by derisen** [comment]
Oh I understand your concern, but I wouldn't worry about it: Azure AD handles around a few billion requests everyday! Now how it deals with such scales is beyond me of course, but I would recommend checking out this [blog post](https://techcommunity.microsoft.com/t5/azure-active-directory-identity/azure-ad-under-the-hood-of-our-geo-redundant-highly-available/ba-p/243762#:~:text=At%20a%20high%20level%2C%20Azure,27%20datacenters%20around%20the%20world.&text=Azure%20AD%20also%20has%20a,of%20our%20high%20availability%20strategy.).

**Comment by DarkLite1** [comment]
Awesome! Going for a stateless API simplifies the design a lot! Thank you very much for the information. Closing this one.
