### ISSUE TITLE
The client links in the overview are 404'd

### ISSUE THREAD

**Issue by MonizDave** [Azure-Samples/active-directory-javascript-nodejs-webapi-v2#16]
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Minimal steps to reproduce
> click on either client link in the Overview

### Any log messages given by the failure
> N/A

### Expected/desired behavior
> to be directed to the client application(s) in question

**Comment by derisen** [comment]
@MonizDave thank you very much for catching this. Will change the links and make a PR asap.

**Comment by derisen** [comment]
Links updated. Closing this.
