### ISSUE TITLE
Authentication failed due to: jwt audience is invalid

### ISSUE THREAD

**Issue by Douglasgomes027** [Azure-Samples/active-directory-javascript-nodejs-webapi-v2#18]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

![image](https://user-images.githubusercontent.com/20713512/126011627-2472dcb8-7a04-4cc0-8edd-3c8417c48dcc.png)

{"name":"AzureAD: Bearer Strategy","hostname":"DESKTOP-HT9EEDQ","pid":18344,"level":30,"msg":"`authentication failed due to: jwt audience is invalid`","time":"2021-07-16T21:46:23.124Z","v":0}

`authentication failed due to: jwt audience is invalid
`
When I press HelloAPi I'm getting this error

### Any log messages given by the failure
>
![image](https://user-images.githubusercontent.com/20713512/126011772-62bac4f7-d051-4aac-af68-0f3a7331a7a4.png)

### Expected/desired behavior
>
normal 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jasonnutter** [comment]
@derisen Can you please take a look at this issue, thanks!

**Comment by derisen** [comment]
@Douglasgomes027 so sorry for the late response, I've missed this. Can you please navigate to **Azure portal** > **App registration** > **Your web API registration** > **Manifest** and confirm that `accessTokenAcceptedVersion `is set to **2**.

**Comment by Douglasgomes027** [comment]
Thank you @derisen !
